name: Check Pull Request Title

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(Add|Remove|Refactor|Fix|Document|Update|Implement) #\\d* .*" # Regex the title should match.
          flags: "g"
          helpMessage: "Example: 'Update #3 README.md'"
